In [7]:
import pandas as pd
data = pd.read_csv("/content/heart_failure_clinical_records_dataset.csv")
data.sample(5)

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
90,70.0,0,66,1,45,0,249000.0,0.8,136,1,1,80,0
231,70.0,0,93,0,35,0,185000.0,1.1,134,1,1,208,0
56,70.0,1,75,0,35,0,223000.0,2.7,138,1,1,54,0
91,60.0,0,897,1,45,0,297000.0,1.0,133,1,0,80,0
237,70.0,0,232,0,30,0,173000.0,1.2,132,1,0,210,0

In [2]:
data.shape

(299, 13)

In [11]:
data["DEATH_EVENT"].unique()

array([1, 0])

In [18]:
data.describe()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
count,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.00000,299.000000,299.000000,299.00000,299.000000,299.00000
mean,60.833893,0.431438,581.839465,0.418060,38.083612,0.351171,263358.029264,1.39388,136.625418,0.648829,0.32107,130.260870,0.32107
std,11.894809,0.496107,970.287881,0.494067,11.834841,0.478136,97804.236869,1.03451,4.412477,0.478136,0.46767,77.614208,0.46767
min,40.000000,0.000000,23.000000,0.000000,14.000000,0.000000,25100.000000,0.50000,113.000000,0.000000,0.00000,4.000000,0.00000
25%,51.000000,0.000000,116.500000,0.000000,30.000000,0.000000,212500.000000,0.90000,134.000000,0.000000,0.00000,73.000000,0.00000
50%,60.000000,0.000000,250.000000,0.000000,38.000000,0.000000,262000.000000,1.10000,137.000000,1.000000,0.00000,115.000000,0.00000
75%,70.000000,1.000000,582.000000,1.000000,45.000000,1.000000,303500.000000,1.40000,140.000000,1.000000,1.00000,203.000000,1.00000
max,95.000000,1.000000,7861.000000,1.000000,80.000000,1.000000,850000.000000,9.40000,148.000000,1.000000,1.00000,285.000000,1.00000

In [15]:
data["age"].sort_values().unique()

array([40.   , 41.   , 42.   , 43.   , 44.   , 45.   , 46.   , 47.   ,
       48.   , 49.   , 50.   , 51.   , 52.   , 53.   , 54.   , 55.   ,
       56.   , 57.   , 58.   , 59.   , 60.   , 60.667, 61.   , 62.   ,
       63.   , 64.   , 65.   , 66.   , 67.   , 68.   , 69.   , 70.   ,
       72.   , 73.   , 75.   , 77.   , 78.   , 79.   , 80.   , 81.   ,
       82.   , 85.   , 86.   , 87.   , 90.   , 94.   , 95.   ])

In [20]:
input = data.drop(columns = "DEATH_EVENT")
output = data["DEATH_EVENT"]

In [21]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(input,output,test_size = 0.3)
x_train.shape

(209, 12)

In [23]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()

In [37]:
model.fit(x_train,y_train)
value = model.predict(x_test)
value

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0])

In [38]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(value,y_test)
print("Prediction accuracy: {:.2f}%".format(acc * 100))

Prediction accuracy: 78.89%

In [39]:
data["prediction"] = model.predict(input)
data.sample(10)

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT,prediction
295,55.0,0,1820,0,38,0,270000.00,1.20,139,0,0,271,0,0
31,85.0,0,23,0,45,0,360000.00,3.00,132,1,0,28,1,1
162,63.0,1,582,0,40,0,448000.00,0.90,137,1,1,123,0,0
232,40.0,1,129,0,35,0,255000.00,0.90,137,1,0,209,0,0
281,70.0,0,582,0,40,0,51000.00,2.70,136,1,1,250,0,0
40,70.0,0,582,0,20,1,263358.03,1.83,134,1,1,31,1,1
239,55.0,1,180,0,45,0,263358.03,1.18,137,1,1,211,0,0
104,60.0,0,53,0,50,1,286000.00,2.30,143,0,0,87,0,0
61,50.0,0,318,0,40,1,216000.00,2.30,131,0,0,60,1,1
252,50.0,0,245,0,45,1,274000.00,1.00,133,1,0,215,0,0